name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        env:
          CONIFER_VERSION: 0.2.2
        with:
          path: conifer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: marrip/conifer
          buildargs: CONIFER_VERSION
          tags: ${{ CONIFER_VERSION }}
